AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 16
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/AbcSize:
  Max: 27
  Exclude:
    - 'spec/**/*'
    - 'lib/petstore_api_client/connection.rb' # Connection setup has reasonable complexity

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

# delete_pet, delete_order, validate! are not predicates
Naming/PredicateMethod:
  Enabled: false

# Allow development dependencies in gemspec for better tooling
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow informal comment annotations (Note:, etc.) instead of forcing NOTE:
Style/CommentAnnotation:
  Enabled: false
